import AppKit
import Foundation

/// 通过 `changeCount` 轮询并保存剪切板原始表示。
@MainActor
final class PasteboardMonitor {
    private let historyStore: HistoryStore
    private let settings: SettingsStore
    private var timer: Timer?
    private let pasteboard: NSPasteboard
    private var lastChangeCount: Int
    private let payloadReader = ClipboardPayloadReader()
    private let preparationQueue = ClipboardHistoryPreparationQueue()
    /// 仅在模拟复制 / SnapFlow 写回剪切板期间临时抑制监听。
    private var transientChangeSuppressionDepth = 0

    private let supportedTypes: Set<NSPasteboard.PasteboardType> = [
        .fileURL, .html, .png, .rtf, .string, .tiff,
        .init("public.jpeg"), .init("public.heic"),
    ]
    private let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
        .init("de.petermaurer.TransientPasteboardType"),
        .init("net.antelle.keeweb"),
    ]
    private let ignoredApplications = [
        "com.agilebits.onepassword", "com.1password.1password",
        "com.1password.1password7", "net.antelle.keeweb",
    ]

    init(
        historyStore: HistoryStore,
        settings: SettingsStore,
        pasteboard: NSPasteboard = .general
    ) {
        self.historyStore = historyStore
        self.settings = settings
        self.pasteboard = pasteboard
        self.lastChangeCount = pasteboard.changeCount
    }

    func start(interval: TimeInterval = 0.5) {
        stop()
        lastChangeCount = pasteboard.changeCount
        let timer = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            Task { @MainActor in await self?.poll() }
        }
        // 允许系统合并空闲轮询，降低菜单栏常驻应用的唤醒次数。
        timer.tolerance = max(0, min(interval * 0.25, 0.25))
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// 开始临时抑制剪切板监听；支持嵌套调用。
    func beginTransientChangeSuppression() {
        transientChangeSuppressionDepth += 1
    }

    /// 结束临时抑制，并将当前剪切板版本设为新的监听基线。
    func endTransientChangeSuppression() {
        guard transientChangeSuppressionDepth > 0 else { return }
        transientChangeSuppressionDepth -= 1
        guard transientChangeSuppressionDepth == 0 else { return }
        lastChangeCount = pasteboard.changeCount
    }

    @discardableResult
    func writeToPasteboard(
        _ item: HistoryItem,
        plainText: Bool = false,
        pasteboard: NSPasteboard = .general
    ) -> Bool {
        let plainString = plainText ? item.string : nil
        if plainText, plainString == nil { return false }

        return withTransientChangeSuppression {
            pasteboard.clearContents()

            if plainText {
                guard let string = plainString else { return false }
                return pasteboard.setString(string, forType: .string)
            }

            // 文本和图片分别作为独立 item，避免接收应用把图片当成同一 item 的唯一表示。
            let pasteboardItems = pasteboardContentGroups(for: item)
                .compactMap { makePasteboardItem(from: $0) }
            guard !pasteboardItems.isEmpty else { return false }
            return pasteboard.writeObjects(pasteboardItems)
        }
    }

    /// 将历史内容按接收应用可识别的表示分组：文字、图片、文件。
    func pasteboardContentGroups(
        for item: HistoryItem,
        includeFileContents: Bool = true
    ) -> [[HistoryItemContent]] {
        let imageTypes = Self.imageContentTypeRawValues
        let fileType = NSPasteboard.PasteboardType.fileURL.rawValue
        let textContents = item.contents.filter {
            $0.type != fileType && !imageTypes.contains($0.type)
        }
        let imageContents = item.contents.filter { imageTypes.contains($0.type) }
        let fileContents = item.contents.filter { $0.type == fileType }

        var groups: [[HistoryItemContent]] = []
        if !textContents.isEmpty { groups.append(textContents) }
        if !imageContents.isEmpty { groups.append(imageContents) }
        if includeFileContents {
            groups.append(contentsOf: fileContents.map { [$0] })
        }
        return groups
    }

    /// 只写入一个内容组，供自动粘贴按文字/图片分两次回写。
    @discardableResult
    func writeToPasteboard(
        contents: [HistoryItemContent],
        pasteboard: NSPasteboard = .general
    ) -> Bool {
        guard let pasteboardItem = makePasteboardItem(from: contents) else { return false }
        return withTransientChangeSuppression {
            pasteboard.clearContents()
            return pasteboard.writeObjects([pasteboardItem])
        }
    }

    func poll() async {
        let observedChangeCount = pasteboard.changeCount
        guard observedChangeCount != lastChangeCount else { return }
        lastChangeCount = observedChangeCount

        if transientChangeSuppressionDepth > 0 {
            return
        }
        guard !settings.clipboardPaused else { return }

        let sourceApp = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        guard sourceApp.map({ !ignoredApplications.contains($0) }) ?? true else { return }

        let readResult = await payloadReader.read(
            ClipboardPayloadReadRequest(
                pasteboardName: pasteboard.name.rawValue,
                supportedTypes: Set(supportedTypes.map(\.rawValue)),
                ignoredTypes: Set(ignoredTypes.map(\.rawValue)),
                imageTypes: Self.imageContentTypeRawValues,
                fileType: NSPasteboard.PasteboardType.fileURL.rawValue,
                recordsText: settings.clipboardRecordsText,
                recordsImages: settings.clipboardRecordsImages,
                recordsFiles: settings.clipboardRecordsFiles
            )
        )
        guard !readResult.containsIgnoredType, !readResult.payloads.isEmpty else { return }

        let prepared = await preparationQueue.prepare(readResult.payloads)
        guard !Task.isCancelled,
              pasteboard.changeCount == observedChangeCount,
              transientChangeSuppressionDepth == 0,
              !settings.clipboardPaused
        else {
            return
        }

        await historyStore.insertFromClipboardMonitor(
            preparedClipboardItem: prepared,
            application: sourceApp,
            isUniversalClipboard: readResult.allTypeRawValues.contains("com.apple.is-remote-clipboard")
        )
    }

    private static let imageContentTypeRawValues: Set<String> = [
        NSPasteboard.PasteboardType.png.rawValue,
        NSPasteboard.PasteboardType.tiff.rawValue,
        "public.jpeg",
        "public.heic",
    ]

    private func makePasteboardItem(from contents: [HistoryItemContent]) -> NSPasteboardItem? {
        let pasteboardItem = NSPasteboardItem()
        var wroteContent = false
        for content in contents {
            guard let value = content.value else { continue }
            wroteContent = pasteboardItem.setData(value, forType: .init(content.type)) || wroteContent
        }
        return wroteContent ? pasteboardItem : nil
    }

    @discardableResult
    private func withTransientChangeSuppression<T>(_ operation: () -> T) -> T {
        beginTransientChangeSuppression()
        defer { endTransientChangeSuppression() }
        return operation()
    }
}
